version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: voting_app
      MYSQL_USER: voteuser
      MYSQL_PASSWORD: votepassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: flask-app
    restart: always
    ports:
      - "5001:5001"
    environment:
      DB_HOST: db
      DB_USER: voteuser
      DB_PASSWORD: votepassword
      DB_NAME: voting_app
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db_data:
