version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your-db-password
      MYSQL_DATABASE: voting_app
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: flask-app
    restart: always
    ports:
      - "5001:5001"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: your-db-password
      DB_NAME: voting_app
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db_data:
