CREATE DATABASE IF NOT EXISTS voting_app;

USE voting_app;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS votes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    team VARCHAR(255),
    FOREIGN KEY (user_id) REFERENCES users(id)
);